# Generated by Django 5.2 on 2025-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ação')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL Amigável)')),
                ('descricao_breve', models.TextField(max_length=300, verbose_name='Descrição Breve')),
                ('descricao_completa', models.TextField(verbose_name='Descrição Completa')),
                ('imagem', models.ImageField(blank=True, help_text='Dimensões recomendadas: 800x600 pixels. Formatos: JPG, PNG.', null=True, upload_to='acoes/', verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ação Ativa?')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Dimensões recomendadas: 1920x600 pixels. Formatos: JPG, PNG. Adequadas para banners grandes.', upload_to='carousels/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('base', 'Carrossel Base'), ('home1', 'Carrossel Home 1'), ('home2', 'Carrossel Home 2')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CasoDeAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, help_text='Dimensões recomendadas: 1024x768 pixels. Formatos: JPG, PNG. O arquivo deve ter menos de 2MB.', null=True, upload_to='casos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caso de Ajuda',
                'verbose_name_plural': 'Casos de Ajuda',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Mensagem')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato Recebido',
                'verbose_name_plural': 'Contatos Recebidos',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-id'],
            },
        ),
    ]
