# Generated by Django 5.2 on 2025-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome único para identificar a imagem no código (ex: 'hero_image', 'logo_footer').", max_length=50, unique=True)),
                ('image', models.ImageField(help_text='Carregue a imagem para este item. Dimensões e tipo variam de acordo com o uso.', upload_to='static_images/')),
                ('description', models.CharField(blank=True, help_text="Breve descrição para o atributo 'alt' da imagem.", max_length=200)),
            ],
            options={
                'verbose_name': 'Imagem Estática',
                'verbose_name_plural': 'Imagens Estáticas',
            },
        ),
    ]
