# Generated by Django 5.2 on 2025-05-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ação')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL Amigável)')),
                ('descricao_breve', models.TextField(max_length=300, verbose_name='Descrição Breve')),
                ('descricao_completa', models.TextField(verbose_name='Descrição Completa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='acoes/', verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ação Ativa?')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousels/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('base', 'Carrossel Base'), ('home1', 'Carrossel Home 1'), ('home2', 'Carrossel Home 2')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Insira seu Nome', max_length=200, null=True)),
                ('email', models.EmailField(default='Insira seu Email', max_length=254, null=True)),
                ('telefone', models.CharField(default='Insira um telefone', max_length=20, null=True)),
                ('observacoes', models.TextField(default='Sem observações', null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato Recebido',
                'verbose_name_plural': 'Contatos Recebidos',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
