# Generated by Django 5.2 on 2025-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Insira seu Nome', max_length=200, null=True)),
                ('email', models.EmailField(default='Insira seu Email', max_length=254, null=True)),
                ('telefone', models.CharField(default='Insira um telefone', max_length=20, null=True)),
                ('observacoes', models.TextField(default='Sem observações', null=True)),
            ],
        ),
    ]
