# Generated by Django 5.2 on 2025-08-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_beneficiaria_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Adicione uma foto da pessoa. Dimensões recomendadas: 300x300 pixels. Formatos: JPG, PNG.', null=True, upload_to='depoimentos/'),
        ),
    ]
