# Generated by Django 5.2 on 2025-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
            ],
        ),
    ]
