# Generated by Django 5.2 on 2025-05-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_depoimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Insira um Título', max_length=200, null=True)),
                ('texto', models.TextField(default='Insira um texto', null=True)),
                ('imagem', models.ImageField(null=True, upload_to='static/imagens')),
                ('descricao_imagem', models.CharField(default='Insira a descrição da necessidade', max_length=200, null=True)),
            ],
        ),
    ]
