# Generated by Django 5.2 on 2025-08-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_depoimento_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Relatório Anual de 2024'", max_length=200)),
                ('descricao', models.TextField(help_text='Breve descrição do conteúdo do documento.')),
                ('documento', models.FileField(help_text='Faça upload do arquivo PDF do balanço.', upload_to='balancos/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Balanço Financeiro',
                'verbose_name_plural': 'Balanços Financeiros',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.AddField(
            model_name='beneficiaria',
            name='historico_medico',
            field=models.TextField(blank=True, verbose_name='Histórico Médico Relevante'),
        ),
        migrations.AddField(
            model_name='beneficiaria',
            name='necessidades',
            field=models.TextField(default=0.0, verbose_name='Necessidades Atuais (Enxoval, Alimentos, etc.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='areas_interesse',
            field=models.TextField(blank=True, help_text='Selecione as áreas de atuação do colaborador.', verbose_name='Áreas de Interesse (Ex: Educação, Logística)'),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='endereco',
            field=models.TextField(verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='situacao_gravidez',
            field=models.CharField(help_text="Ex: '7º mês de gestação'", max_length=100, verbose_name='Situação da Gravidez'),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(help_text="Ex: 'Voluntário', 'Coordenador'", max_length=100, verbose_name='Cargo / Função'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Conta de Usuário'),
        ),
    ]
