# Generated by Django 5.2 on 2025-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_missao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ação')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL Amigável)')),
                ('descricao_breve', models.TextField(max_length=300, verbose_name='Descrição Breve')),
                ('descricao_completa', models.TextField(verbose_name='Descrição Completa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='acoes/', verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ação Ativa?')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
