# Generated by Django 5.2 on 2025-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_balancofinanceiro_beneficiaria_historico_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Política de Transparência do Projeto Sarah'", max_length=200)),
                ('documento', models.FileField(help_text='Faça upload do arquivo PDF da política.', upload_to='politicas/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Política de Transparência',
                'verbose_name_plural': 'Políticas de Transparência',
            },
        ),
    ]
